/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.sistemamedicioncliente.presentacion;

import co.unicauca.sistemamedicion.cliente.acceso.FabricaItemMedicion;
import co.unicauca.sistemamedicion.cliente.doominio.servicio.ServicioMedicion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import co.unicauca.sistemamedicion.cliente.acceso.IServicioItemMedicion;
import co.unicauca.sistemamedicion.cliente.dominio.Disparador;
import co.unicauca.sistemamedicion.comun.dominio.LataCerveza;

/**
 *
 * @author mfcaicedo
 */
public class GUIItemMedicion extends javax.swing.JInternalFrame {
    
    /**
     * Atributos 
     */
    ServicioMedicion servicioMedicion;
    /**
     * Creates new form GUIItemMedicion
     */
    public GUIItemMedicion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jButtonIniciarSimulacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPaneInfoDatosOptimos = new javax.swing.JScrollPane();
        jTableInfoElementOptimos = new javax.swing.JTable();
        jScrollPaneInfoElementDefectuosos = new javax.swing.JScrollPane();
        jTableInfoElementDefectuosos = new javax.swing.JTable();
        jLabelAltura = new javax.swing.JLabel();
        jtxtAltura = new javax.swing.JTextField();
        jLabelAncho = new javax.swing.JLabel();
        jtxtAncho = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jtxtPeso = new javax.swing.JTextField();
        jButtonMuestra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButtonIniciarSimulacion.setText("Iniciar simulación");
        jButtonIniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSimulacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Tabla de resultados ");

        jLabel3.setText("Elementos en estado Optimo");

        jLabel4.setText("Elementos en estado defectuoso");

        jTableInfoElementOptimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneInfoDatosOptimos.setViewportView(jTableInfoElementOptimos);

        jTableInfoElementDefectuosos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneInfoElementDefectuosos.setViewportView(jTableInfoElementDefectuosos);

        jLabelAltura.setText("Altura:");

        jtxtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAlturaActionPerformed(evt);
            }
        });

        jLabelAncho.setText("Ancho:");

        jLabelPeso.setText("Peso:");

        jButtonMuestra.setText("Enviar muestra");
        jButtonMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuestraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButtonIniciarSimulacion)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCentralLayout.createSequentialGroup()
                                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAltura)
                                    .addComponent(jLabelAncho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(jtxtAncho))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                                        .addComponent(jLabelPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonMuestra)))
                            .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPaneInfoDatosOptimos, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPaneInfoElementDefectuosos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonIniciarSimulacion)
                .addGap(33, 33, 33)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAltura)
                    .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPeso)
                        .addComponent(jtxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAncho)
                    .addComponent(jtxtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMuestra))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneInfoElementDefectuosos, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jScrollPaneInfoDatosOptimos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Mostrar datos del resultado 
     * @param 
     */
    public void mostrarInfoResultado(){
        
    }
    
    private void deteccionElemento(){
        String peticion = "start";
        IServicioItemMedicion objItemMedicion;
        Disparador objDisparador;
        objItemMedicion = FabricaItemMedicion.getInstance().obtenerItemMedicion();
        objDisparador = FabricaItemMedicion.getInstance().obtenerDisparador();
        objDisparador.deteccionElemento(peticion);
        // Inyecta la dependencia
        servicioMedicion = new ServicioMedicion(objItemMedicion);
        
        //Eviamos la alerta
        String respuesta = "";
        try {
            respuesta = servicioMedicion.deteccionElemento(objDisparador); 
        } catch (Exception ex) {
            Logger.getLogger(GUIItemMedicion.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Según la respuesta del servidor tomo decisiones 
        if (respuesta.equals("datos")) {
            //Eviamos los datos de la muestra al servidor
            JOptionPane.showMessageDialog(this, respuesta,"Respuesta servidor",JOptionPane.INFORMATION_MESSAGE);
            
            
            
        }else{
            //mostrar información 
            JOptionPane.showMessageDialog(this, respuesta,"Respuesta servidor",JOptionPane.INFORMATION_MESSAGE);
            mostrarInfoResultado();
        }  
    }
    private void recolectarDatos(){
        if (servicioMedicion != null) {
            
            LataCerveza objCerveza = new LataCerveza();   
            try{
                if (this.jtxtAltura.getText() != null && this.jtxtAncho.getText() != "" && this.jtxtPeso.getText() != "" ) {
                    objCerveza.setAltura(Float.parseFloat(this.jtxtAltura.getText()));
                    objCerveza.setAncho(Float.parseFloat(this.jtxtAncho.getText()));
                    objCerveza.setPeso(Float.parseFloat(this.jtxtPeso.getText()));
                    
                    String respuesta = servicioMedicion.recoleccionDatos(objCerveza);
                    
                    //if (respuesta.equals("listo")) {
                        JOptionPane.showMessageDialog(this, respuesta,"Respuesta servidor",JOptionPane.INFORMATION_MESSAGE);
                    //}else{
                      //  System.out.println("no entra al if");
                   // }
                }
                
            }catch(Exception e){
                System.out.println("Verificar datos");
            }
            
        }
        
    }
    
    
    /**
     * Accion del disparador 
     * @param evt 
     */
    private void jButtonIniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSimulacionActionPerformed
        
        // TODO add your handling code here:
         deteccionElemento();
    }//GEN-LAST:event_jButtonIniciarSimulacionActionPerformed

   
    
    private void jtxtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAlturaActionPerformed
    /**
    * Accion del boton muestra de datos 
    * @param evt 
    */
    private void jButtonMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuestraActionPerformed
        // TODO add your handling code here:
        recolectarDatos();
    }//GEN-LAST:event_jButtonMuestraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarSimulacion;
    private javax.swing.JButton jButtonMuestra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelAncho;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JScrollPane jScrollPaneInfoDatosOptimos;
    private javax.swing.JScrollPane jScrollPaneInfoElementDefectuosos;
    private javax.swing.JTable jTableInfoElementDefectuosos;
    private javax.swing.JTable jTableInfoElementOptimos;
    private javax.swing.JTextField jtxtAltura;
    private javax.swing.JTextField jtxtAncho;
    private javax.swing.JTextField jtxtPeso;
    // End of variables declaration//GEN-END:variables

}
